version: '3.8'
services:
    wordpress:
        image: wordpress:5.7.1-php8.0-apache
        volumes:
            - ./main:/var/www/html
            - ./wp-content:/var/www/html/wp-content
            - ./.htaccess:/var/www/html/.htaccess
        expose:
            - $WP_POR
        ports:
            - $WP_PORT:80
        depends_on:
            - mysql
        environment:
            - WORDPRESS_DB_HOST=mysql:3306
            - WORDPRESS_DB_USER=$WP_MYSQL_USERNAME
            - WORDPRESS_DB_PASSWORD=$WP_MYSQL_PASSWORD
            - WORDPRESS_DB_NAME=$WP_MYSQL_DATABASE
            - WORDPRESS_CONFIG_EXTRA=
                define('WP_SITEURL', 'http://localhost:$WP_PORT');
                define('WP_HOME', 'http://localhost:$WP_PORT');
                define('WP_DEBUG', $WP_DEBUG_LOG);
                define('WP_ENVIRONMENT_TYPE', 'development' );

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql:3306
            - PMA_ARBITRARY=1
        ports:
            - $WP_PORT_PHP_MY_ADMIN:80

    mysql:
        image: mysql:8
        volumes:
            - ./SQL/dump-newest.sql:/docker-entrypoint-initdb.d/dump-newest.sql
        environment:
            - MYSQL_ROOT_PASSWORD=$WP_MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=$WP_MYSQL_DATABASE
            - MYSQL_USER=$WP_MYSQL_USERNAME
            - MYSQL_PASSWORD=$WP_MYSQL_PASSWORD
