version: '3.8'
services:
    wordpress:
        container_name: ${COMPOSE_PROJECT_NAME}_wordpress
        image: wordpress:latest
        volumes:
            - ./wordpress:/var/www/html
            - ./wordpress/.htaccess:/var/www/html/.htaccess
        expose:
            - $WP_PORT
        ports:
            - $WP_PORT:80
        depends_on:
            - mysql
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: $WP_MYSQL_USERNAME
            WORDPRESS_DB_PASSWORD: $WP_MYSQL_PASSWORD
            WORDPRESS_DB_NAME: $WP_MYSQL_DATABASE
            WORDPRESS_DEBUG: $WP_DEBUG
            WORDPRESS_CONFIG_EXTRA: |
                define('WP_SITEURL', 'http://localhost:$WP_PORT');
                define('WP_HOME', 'http://localhost:$WP_PORT');
                define('BS_WEBPACK_PORT', $WEBPACK_PORT);

    phpmyadmin:
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql:3306
            - PMA_ARBITRARY=1
        ports:
            - $WP_PORT_PHP_MY_ADMIN:80

    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        image: mysql:8
        volumes:
            - ./SQL/dump-newest.sql:/docker-entrypoint-initdb.d/dump-newest.sql
        environment:
            MYSQL_ROOT_PASSWORD: $WP_MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $WP_MYSQL_DATABASE
            MYSQL_USER: $WP_MYSQL_USERNAME
            MYSQL_PASSWORD: $WP_MYSQL_PASSWORD
